name: C/C++ CI

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:
    inputs:
      reason:
        description: 'A reason to trigger this workflow.'
        required: true
        default: 'Re-run workflow.'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Setup premake
        uses: abel0b/setup-premake@v1
        
      - name: Compile it
        shell: cmd
        run: | 
           premake5 vs2019
           msbuild ngrok-helper/ngrok-helper.vcxproj -p:Platform=Win32;Configuration=Release
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: milima-artifacts-x86
          path: bin/Release/ngrok-helper.exe

